# Generated by Django 4.2.1 on 2023-07-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teetimebot', '0002_rename_phone_numer_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseschedule',
            old_name='booking_class_id',
            new_name='booking_class',
        ),
    ]
