# Generated by Django 4.2.1 on 2023-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teetimebot', '0004_alter_userteetimerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteetimerequest',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('pending', 'Pending')], default='inactive', max_length=20),
        ),
    ]
