# Generated by Django 4.2.1 on 2023-08-03 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teetimebot', '0010_historicalmatchingteetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatchingteetime',
            name='course_schedule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='teetimebot.courseschedule'),
        ),
        migrations.AddField(
            model_name='matchingteetime',
            name='course_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='teetimebot.courseschedule'),
            preserve_default=False,
        ),
    ]
