# Generated by Django 4.2.1 on 2023-08-05 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teetimebot", "0011_historicalmatchingteetime_course_schedule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchingteetimenotification",
            name="sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usernotifications",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
