# Generated by Django 4.2.1 on 2023-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teetimebot", "0013_matchingteetime_unique_matching_teetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usernotifications",
            name="push",
        ),
        migrations.AlterField(
            model_name="usernotifications",
            name="text",
            field=models.BooleanField(default=True),
        ),
    ]
