# Generated by Django 4.2.1 on 2023-08-08 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teetimebot", "0014_remove_usernotifications_push_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchingteetimenotification",
            old_name="to_phone_numer",
            new_name="to_phone_number",
        ),
    ]
