# Generated by Django 4.2.1 on 2023-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "teetimebot",
            "0017_remove_userteetimerequest_both_fields_null_or_filled_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotifications",
            name="text",
            field=models.BooleanField(default=False),
        ),
    ]
