# Generated by Django 4.2.1 on 2023-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teetimebot", "0018_alter_usernotifications_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userteetimerequest",
            name="days",
            field=models.CharField(
                blank=True,
                choices=[
                    ("every day", "Every day"),
                    ("every friday", "Every Friday"),
                    ("weekdays", "Weekdays"),
                    ("weekends", "Weekends"),
                    ("today", "Today"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
