# Generated by Django 4.2.1 on 2023-08-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teetimebot", "0020_courseschedule_console_facility_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userteetimerequest",
            name="course_schedules",
            field=models.ManyToManyField(blank=True, to="teetimebot.courseschedule"),
        ),
    ]
