# Generated by Django 4.2.1 on 2023-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teetimebot", "0021_userteetimerequest_course_schedules"),
    ]

    operations = [
        migrations.AddField(
            model_name="userteetimerequest",
            name="group_id",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
